class UnexpectedError(Exception):
    ...

class AbstractError(Exception):
    ...

class FieldRequirementException(Exception):
    ...

class ValidationError(Exception):
    ...

class NativeValidationError(ValidationError):
    ...

class NotNoneError(NativeValidationError):
    ...